version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: docstorage-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  
  redis:
    image: redis:latest
    container_name: docstorage-redis
    ports:
      - 6379:6379 

  minio:
    image: minio/minio:latest
    container_name: test-api-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    restart: always
    command: server /data --console-address ":9001"

volumes:
  minio_data:
    driver: local